### ISSUE TITLE
Define automatic release process

### ISSUE THREAD

**Issue by Simply007** [Kentico/delivery-sdk-ruby#15]
### Motivation

Define how to deploy a new version of GEM.

### Proposed solution

Extend Travis CI configuration of the Deploy step. 
Use the tag release trigger.

That allows all people to create a new version to the gem.

### Additional context

* https://docs.travis-ci.com/user/deployment/rubygems/
* https://travis-ci.org/Kentico/delivery-sdk-ruby

**Comment by Simply007** [comment]
This require @kentico-ericd's API key.
* We will set this up together

**Comment by kentico-ericd** [comment]
@Simply007 I think everything's set up correctly, but travis still reports:

> Skipping a deployment with the rubygems provider because this is not a tagged commit

Though I've used `git tag` on the recent commit and `git show v0.14.4` shows:

> $ git show v0.14.4
> tag v0.14.4
> Tagger: Eric Dugre
> Date:   Fri Mar 8 14:30:20 2019 -0500
> 
> 0.14.4
> 
> commit 3ca2d3be7a7619e571963344417ba63b10445c54 (HEAD -> master, tag: v0.14.4, origin/master, origin/HEAD)
> Author: Eric Dugre
> Date:   Fri Mar 8 14:30:07 2019 -0500
> 
>     Update version again- testing Travis
> 
> diff --git a/lib/delivery/version.rb b/lib/delivery/version.rb
> index 2b7ddb7..18eb341 100644
> --- a/lib/delivery/version.rb
> +++ b/lib/delivery/version.rb
> @@ -1,3 +1,3 @@
>  module Delivery
> -  VERSION = '0.14.3'.freeze
> +  VERSION = '0.14.4'.freeze
>  end

**Comment by Simply007** [comment]
@kentico-ericd,

you might not push the tags to the repository using `git push origin <tagname>`. So that tags are only on your local repository. 

I would recommend creating another wiki page similar as [that](https://github.com/Kentico/gatsby-source-kentico-cloud/wiki/How-to-publish-new-version-of-the-source-plugin) and describing, how to make the new release from the Github UI from [Releases](https://github.com/Kentico/delivery-sdk-ruby/releases) section.

I would also vote for storing the key environment variable on Travis and use it like [here](https://github.com/Kentico/kentico.github.io/blob/source/.travis.yml#L14). I know that the key is encrypted, but it is more flexible to be able to change it (i.e. in case of revoking) without the commit.

**Comment by kentico-ericd** [comment]
Automated publishing with tagged commits seems to be working now. I will update the documentation/wiki 👍
