### ISSUE TITLE
Define Ruby capabilities

### ISSUE THREAD

**Issue by Simply007** [Kentico/delivery-sdk-ruby#18]
### Expected result

Have the section in the official KenticoCloud documentation (as it is for i.e. [PHP](https://developer.kenticocloud.com/docs/php))

### Additional context

We would like to have the section filled for the Ruby SDK.
We need information/links to the page:
* Link to the repository
* Link to the package in package manager (gem)
* Links to the documentation (readme) to be able to fill [Supported features](https://developer.kenticocloud.com/docs/php#section-supported-features)
* Provide the link to the sample application
* Provide link(s) to the blog post about the Ruby

**Comment by kentico-ericd** [comment]
|Feature|Availability|Documentation|
|--|--|--|
|Retrieve content items|✔️ |[View docs](https://github.com/Kentico/delivery-sdk-ruby#listing-items)
|Secure access|✔️ |[View docs](https://github.com/Kentico/delivery-sdk-ruby#listing-items)
||✔️ |[View docs](https://github.com/Kentico/delivery-sdk-ruby#listing-items)
||✔️ |[View docs](https://github.com/Kentico/delivery-sdk-ruby#listing-items)
||✔️ |[View docs](https://github.com/Kentico/delivery-sdk-ruby#listing-items)
||✔️ |[View docs](https://github.com/Kentico/delivery-sdk-ruby#listing-items)
||✔️ |[View docs](https://github.com/Kentico/delivery-sdk-ruby#listing-items)
||✔️ |[View docs](https://github.com/Kentico/delivery-sdk-ruby#listing-items)
||✔️ |[View docs](https://github.com/Kentico/delivery-sdk-ruby#listing-items)

**Comment by kentico-ericd** [comment]
|Feature|Availability|Documentation|
|--|--|--|
|Retrieve content items|✔️ |[View docs](https://github.com/Kentico/delivery-sdk-ruby#listing-items)
|Secure access|✔️ |[View docs](https://github.com/Kentico/delivery-sdk-ruby#making-secure-requests)
|Preview unpublished content items|✔️ |[View docs](https://github.com/Kentico/delivery-sdk-ruby#previewing-unpublished-content)
|Filter content items|✔️ |[View docs](https://github.com/Kentico/delivery-sdk-ruby#filtering)
|Localization|✔️ |[View docs](https://github.com/Kentico/delivery-sdk-ruby#parameters)
|Retrieve linked items and items in Rich text|✔️ |[View docs](https://github.com/Kentico/delivery-sdk-ruby#linked-items)
|Retrieve content as strongly-typed models| |
|Render components and items in Rich text|✔️ |[View docs](https://github.com/Kentico/delivery-sdk-ruby#resolving-inline-content)
|Resolve links to content items in Rich text|✔️ |[View docs](https://github.com/Kentico/delivery-sdk-ruby#resolving-links)
|Retrieve taxonomy groups|✔️ |[View docs](https://github.com/Kentico/delivery-sdk-ruby#taxonomy)
|Custom elements|✔️ |
|Webhook support|✔️ |

**Comment by kentico-ericd** [comment]
Not sure what "Custom elements" support should look like, but if it means you can request a custom element using [https://github.com/Kentico/delivery-sdk-ruby#retreiveing-content-type-elements](this) then it should work fine.

**Comment by petrsvihlik** [comment]
ability to retrieve data from custom elements (some SDKs were crashing when we added custom elements to the API)

**Comment by Simply007** [comment]
Just add the note that Custom elements are supported to the [Readme](https://github.com/Kentico/delivery-sdk-ruby#retrieving-content-type-elements). And then link it to the table.

Thanks @kentico-ericd!

**Comment by kentico-ericd** [comment]
@Simply007 👍 done!

**Comment by Simply007** [comment]
Awesome! 

After it is closed, I think it is the time for 1.0.0 release - what do you think @kentico-ericd ?
