### ISSUE TITLE
Incorrect parsing of modular content

### ISSUE THREAD

**Issue by RadoslavK** [Kentico/delivery-sdk-ruby#2]
Hello, I have noticed you are incorrectly parsing the modular content of content items queries.

The model of a [listing response](https://developer.kenticocloud.com/v1/reference#listing-response) differs from the model of a [single content item](https://developer.kenticocloud.com/v1/reference#content-item-object). Modular content is always on the first level of response, therefore if the list is queried it can no longer parse modular content from the level of the particular content item.

Currently, it is being parsed in the same way which results in incorrect behavior of retrieving links from such items.

To give an idea about the problem, I have fixed it on my branch. [commit](https://github.com/RadoslavK/delivery-sdk-ruby/commit/050d1bebb10ab69ce959a80ae60034c68f8e14b9)

**Comment by kentico-ericd** [comment]
Solved in [010d258](https://github.com/RadoslavK/delivery-sdk-ruby/commit/010d25844b0c6f0139d828b46be4ec97ace763a4)

Honestly didn't even notice you forked it until I fixed >_<
