### ISSUE TITLE
Resolvers do not support templating languages

### ISSUE THREAD

**Issue by RadoslavK** [Kentico/delivery-sdk-ruby#23]
I am not sure if it is by design or just not thought of

My case
1. The link resolver returns this url `{{ site.pages | where_exp: 'page', 'page.data.system.id == link_id' | map: 'url' | first | relative_url }}`

2. Nokogiri escapes special characters

3. Result cannot be further processed by a templating language such as Liquid

Naive solution: Once the content/link is resolved, call `doc.to_xhtml` instead of `doc.inner_html` which is not escaping the anchor href attribute value.

**Comment by kentico-ericd** [comment]
Couldn't reproduce in `InlineContentItemResolver`, but did with `ContentLinkResolver` so the fix is implemented there. Thanks @RadoslavK!
