### ISSUE TITLE
Make get_element in content_item.rb to accept symbols

### ISSUE THREAD

**Issue by RadoslavK** [Kentico/delivery-sdk-ruby#24]
`elements` return an _OpenStruct_ object which means all element codename keys are transformed to symbols. So if you iterate over them and eg want to get links or assets you need to convert the key to string yourself which is not intuitive and annoying.

The symbol can be easily converted to a string to work with the internal data structure.

**Comment by kentico-ericd** [comment]
@RadoslavK can you please show me an example of what you're doing in code when you need to convert the key to a string?

**Comment by kentico-ericd** [comment]
@RadoslavK nvm, I see you're talking about something like this:

```
response.item.elements.to_h.each do |k,v|
  puts k == 'title' #false every time
end
```
