### ISSUE TITLE
Fix Travis

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/delivery-sdk-ruby#6]
Fix the failing builds in Travis:
- https://travis-ci.com/Kentico/delivery-sdk-ruby/builds

**Comment by kentico-ericd** [comment]
I'm afraid I'm not very familiar with Travis- it came with the new gem. Some searching on the web said that I needed to modify the PLATFORMS section of the Gemfile.lock which [I tried](https://github.com/Kentico/delivery-sdk-ruby/commit/d3e43bfed6cb36919a0e3d5dc751b0d29611772d) and now I'm getting a new error in Travis:

> Unable to find a spec satisfying nokogiri (>= 1.8.4, ~> 1.10.0) in the set.
Perhaps the lockfile is corrupted? Found nokogiri (1.10.1-x86-mingw32), nokogiri
(1.10.1-x64-mingw32) that did not match the current platform.

TBH, I'm not even sure my gem is usable on linux. Why was Travis even trying to build on linux when the only platform in the Gemfile.lock was "x64-mingw32" from the start?

**Comment by petrsvihlik** [comment]
No idea... Let's wait for someone more experienced to fix it :)

**Comment by petrsvihlik** [comment]
@RadoslavK would you like to have a look at this one?

it'd be also great to have an automated gem publishing process

**Comment by petrsvihlik** [comment]
@Simply007 already started working on it

**Comment by Simply007** [comment]
* Removed gemfile.loc (https://stackoverflow.com/questions/4151495/should-gemfile-lock-be-included-in-gitignore)
* Used environment variables for project API keys (project: faf446d2-0544-0039-bb43-5d6ef816661a)

.. I have done commits right into the master - Will create a pull request and squash commits next time.

Created a new issue for automatic build process #15
